expected_paths = [
    "images/GICA25/SE_subj1_sess1_FCtICA1_IC 2.png",
    "images/GICA25/SE_subj1_sess1_FCtICA2_IC 2.png",
    "images/GICA25/SE_subj1_sess1_tICA_IC 2.png",
    "images/GICA25/SE_subj3_sess1_FCtICA1_IC 2.png",
    "images/GICA25/SE_subj3_sess1_FCtICA2_IC 2.png",
    "images/GICA25/SE_subj3_sess1_tICA_IC 2.png",
    "images/GICA25/S_ICC_DR_IC 1.png",
    "images/GICA25/S_ICC_DR_IC 2.png",
    "images/GICA25/S_ICC_DR_IC 8.png",
    "images/GICA25/S_ICC_FCtICA1_IC 1.png",
    "images/GICA25/S_ICC_FCtICA1_IC 2.png",
    "images/GICA25/S_ICC_FCtICA1_IC 8.png",
    "images/GICA25/S_ICC_FCtICA2_IC 1.png",
    "images/GICA25/S_ICC_FCtICA2_IC 2.png",
    "images/GICA25/S_ICC_FCtICA2_IC 8.png",
    "images/GICA25/S_ICC_tICA_IC 1.png",
    "images/GICA25/S_ICC_tICA_IC 2.png",
    "images/GICA25/S_ICC_tICA_IC 8.png",
    "images/GICA25/S_subj1_sess1_DR_IC 2.png",
    "images/GICA25/S_subj1_sess1_FCtICA1_IC 2.png",
    "images/GICA25/S_subj1_sess1_FCtICA2_IC 2.png",
    "images/GICA25/S_subj1_sess1_tICA_IC 2.png",
    "images/GICA25/S_subj3_sess1_DR_IC 2.png",
    "images/GICA25/S_subj3_sess1_FCtICA1_IC 2.png",
    "images/GICA25/S_subj3_sess1_FCtICA2_IC 2.png",
    "images/GICA25/S_subj3_sess1_tICA_IC 2.png",
    "images/SE_legend.png",
    "images/S_ICC_legend.png",
    "images/S_legend.png",
    "plots/FC_ICC_change_legend.pdf",
    "plots/FC_ICC_legend.pdf",
    "plots/GICA25/FC_ICC.pdf",
    "plots/GICA25/FC_ICC_change.pdf",
    "plots/GICA25/FC_dist.pdf",
    "plots/GICA25/FC_empirical.pdf",
    "plots/GICA25/FC_subj1_sess1.pdf",
    "plots/GICA25/FC_subj2_sess1.pdf",
    "plots/GICA25/FC_subj3_sess1.pdf",
    "plots/GICA25/FC_template_Chol.pdf",
    "plots/GICA25/FC_template_IW.pdf",
    "plots/S_ICC_vs_tICA.pdf",
    "response/MSE_TCs.pdf",
    "response/MSE_truth_prior.pdf",
    "simulation/TCs_real/TCs.pdf",
    "simulation/TCs_real/TCs_real_FC.pdf",
    "simulation/exampleICs/subject1_IC1.png",
    "simulation/exampleICs/subject1_IC2.png",
    "simulation/exampleICs/subject1_IC3.png",
    "simulation/exampleICs/subject1_IC4.png",
    "simulation/exampleICs/subject1_IC5.png",
    "simulation/exampleICs/subject1_dev1.png",
    "simulation/exampleICs/subject1_dev2.png",
    "simulation/exampleICs/subject1_dev3.png",
    "simulation/exampleICs/subject1_dev4.png",
    "simulation/exampleICs/subject1_dev5.png",
    "simulation/images/MAE/MAE_DR_IC 1.png",
    "simulation/images/MAE/MAE_DR_IC 2.png",
    "simulation/images/MAE/MAE_DR_IC 3.png",
    "simulation/images/MAE/MAE_DR_IC 4.png",
    "simulation/images/MAE/MAE_DR_IC 5.png",
    "simulation/images/MAE/MAE_VB1_IC 1.png",
    "simulation/images/MAE/MAE_VB1_IC 2.png",
    "simulation/images/MAE/MAE_VB1_IC 3.png",
    "simulation/images/MAE/MAE_VB1_IC 4.png",
    "simulation/images/MAE/MAE_VB1_IC 5.png",
    "simulation/images/MAE/MAE_VB2_IC 1.png",
    "simulation/images/MAE/MAE_VB2_IC 2.png",
    "simulation/images/MAE/MAE_VB2_IC 3.png",
    "simulation/images/MAE/MAE_VB2_IC 4.png",
    "simulation/images/MAE/MAE_VB2_IC 5.png",
    "simulation/images/MAE/MAE_tICA_IC 1.png",
    "simulation/images/MAE/MAE_tICA_IC 2.png",
    "simulation/images/MAE/MAE_tICA_IC 3.png",
    "simulation/images/MAE/MAE_tICA_IC 4.png",
    "simulation/images/MAE/MAE_tICA_IC 5.png",
    "simulation/images/examples/legend.png",
    "simulation/images/examples/testsubj1_Sdev_DR_IC 4.png",
    "simulation/images/examples/testsubj1_Sdev_VB1_IC 4.png",
    "simulation/images/examples/testsubj1_Sdev_VB2_IC 4.png",
    "simulation/images/examples/testsubj1_Sdev_tICA_IC 4.png",
    "simulation/images/examples/testsubj1_Sdev_true_IC 4.png",
    "simulation/images/examples/testsubj2_Sdev_DR_IC 4.png",
    "simulation/images/examples/testsubj2_Sdev_VB1_IC 4.png",
    "simulation/images/examples/testsubj2_Sdev_VB2_IC 4.png",
    "simulation/images/examples/testsubj2_Sdev_tICA_IC 4.png",
    "simulation/images/examples/testsubj2_Sdev_true_IC 4.png",
    "simulation/images/examples/testsubj3_Sdev_DR_IC 4.png",
    "simulation/images/examples/testsubj3_Sdev_VB1_IC 4.png",
    "simulation/images/examples/testsubj3_Sdev_VB2_IC 4.png",
    "simulation/images/examples/testsubj3_Sdev_tICA_IC 4.png",
    "simulation/images/examples/testsubj3_Sdev_true_IC 4.png",
    "simulation/legend_FC.pdf",
    "simulation/legend_FC_SD.pdf",
    "simulation/legend_FC_mean.pdf",
    "simulation/legend_MAE_FC.pdf",
    "simulation/legend_MAE_FC_byduration.pdf",
    "simulation/legend_MAE_FC_diff.pdf",
    "simulation/plots/FC_CIs.pdf",
    "simulation/plots/FC_mean_and_SD.pdf",
    "simulation/plots/MAE_FC.pdf",
    "simulation/plots/MAE_FC_byduration.pdf",
    "simulation/plots/MAE_FC_byduration_DR.pdf",
    "simulation/plots/MAE_FC_byduration_VB1.pdf",
    "simulation/plots/MAE_FC_byduration_VB2.pdf",
    "simulation/plots/MAE_FC_byduration_tICA.pdf",
    "simulation/plots/MAE_FC_diff_DR.pdf",
    "simulation/plots/MAE_FC_diff_tICA.pdf",
    "simulation/plots/testsubj1FC.pdf",
    "simulation/plots/testsubj2FC.pdf",
    "simulation/plots/testsubj3FC.pdf",
    "simulation/templates/FCtemplate.pdf",
    "simulation/templates/FCtemplate2.pdf",
    "simulation/templates/generating_mean1.png",
    "simulation/templates/generating_mean2.png",
    "simulation/templates/generating_mean3.png",
    "simulation/templates/generating_mean4.png",
    "simulation/templates/generating_mean5.png",
    "simulation/templates/generating_var1.png",
    "simulation/templates/generating_var2.png",
    "simulation/templates/generating_var3.png",
    "simulation/templates/generating_var4.png",
    "simulation/templates/generating_var5.png",
    "simulation/templates/template_est_mean_IC 1.png",
    "simulation/templates/template_est_mean_IC 2.png",
    "simulation/templates/template_est_mean_IC 3.png",
    "simulation/templates/template_est_mean_IC 4.png",
    "simulation/templates/template_est_mean_IC 5.png",
    "simulation/templates/template_est_var_IC 1.png",
    "simulation/templates/template_est_var_IC 2.png",
    "simulation/templates/template_est_var_IC 3.png",
    "simulation/templates/template_est_var_IC 4.png",
    "simulation/templates/template_est_var_IC 5.png",
    "simulation/templates/template_mean1.png",
    "simulation/templates/template_mean2.png",
    "simulation/templates/template_mean3.png",
    "simulation/templates/template_mean4.png",
    "simulation/templates/template_mean5.png",
    "simulation/templates/template_var1.png",
    "simulation/templates/template_var2.png",
    "simulation/templates/template_var3.png",
    "simulation/templates/template_var4.png",
    "simulation/templates/template_var5.png",
    "templates/GICA25/GICA_IC1_thr.png",
    "templates/GICA25/GICA_IC2_thr.png",
    "templates/GICA25/GICA_IC3_thr.png",
    "templates/GICA25/GICA_IC4_thr.png",
    "templates/GICA25/GICA_IC5_thr.png",
    "templates/GICA25/GICA_IC6_thr.png",
    "templates/GICA25/GICA_IC7_thr.png",
    "templates/GICA25/GICA_IC8_thr.png",
    "templates/GICA25/GICA_IC9_thr.png",
    "templates/GICA25/GICA_IC10_thr.png",
    "templates/GICA25/GICA_IC11_thr.png",
    "templates/GICA25/GICA_IC12_thr.png",
    "templates/GICA25/GICA_IC13_thr.png",
    "templates/GICA25/GICA_IC14_thr.png",
    "templates/GICA25/GICA_IC15_thr.png",
    "templates/GICA25/GICA_IC16_thr.png",
    "templates/GICA25/GICA_IC17_thr.png",
    "templates/GICA25/GICA_IC18_thr.png",
    "templates/GICA25/GICA_IC19_thr.png",
    "templates/GICA25/GICA_IC20_thr.png",
    "templates/GICA25/GICA_IC21_thr.png",
    "templates/GICA25/GICA_IC22_thr.png",
    "templates/GICA25/GICA_IC23_thr.png",
    "templates/GICA25/GICA_IC24_thr.png",
    "templates/GICA25/GICA_IC25_thr.png",
    "templates/template25/template_mean_IC1.png",
    "templates/template25/template_mean_IC2.png",
    "templates/template25/template_mean_IC8.png",
    "templates/template25/template_mean_IC10.png",
    "templates/template25/template_mean_IC16.png",
    "templates/template25/template_var_IC1.png",
    "templates/template25/template_var_IC2.png",
    "templates/template25/template_var_IC8.png",
    "templates/template25/template_var_IC10.png",
    "templates/template25/template_var_IC16.png",
    "templates/template_mean_legend.png",
    "templates/template_var_legend.jpg"
]